[build]
  ignore = "/bin/false"
  base = ".markpub"
  publish = "../output"
  command = "markpub build -i .. -o ../output --templates ./this-website-themes/andante --lunr --commits"

[build.environment]
  PYTHON_VERSION = "3.11"
